version: "3"
services:
  postgresdb:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=thymeleaf
    ports:
      - "5432:5432"
    volumes:
      - data:/data
volumes:
  data: {}